language: python

python:
- 2.7
- 3.5

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt

before_script:
#- pip install wechatsogou
- export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
- if [[ $OCR_RUOKUAI ]]; then python test/ruokuaicode_test.py $OCR_RUOKUAI $RUOKUAI_USERNAME $RUOKUAI_PASSWORD $RUOKUAI_SOFT_ID $RUOKUAI_SOFT_KEY; fi
- if [[ $OCR_RUOKUAI ]]; then python test/api_test.py $OCR_RUOKUAI $RUOKUAI_USERNAME $RUOKUAI_PASSWORD $RUOKUAI_SOFT_ID $RUOKUAI_SOFT_KEY; fi